### ISSUE TITLE
stm32 sprintf float value

### ISSUE THREAD

**Issue by edirab** [quen0n/DHT11-DHT22-STM32-HAL#1]
Доброго времени суток! 
Уважаемый автор, добавьте, пожалуйста, в файл readme указание о необходимости включения флага
**-u _printf_float**
в опциях линкера и ссылку на данный вопрос на stackoverflow:
https://stackoverflow.com/questions/28334435/stm32-printf-float-variable

Думаю, это кому-нибудь поможет)

**Comment by quen0n** [comment]
Здравствуйте

Обновил readme, спасибо :)
