### ISSUE TITLE
i have problem with blue pill or black pill with DHT11,always get int only. always xx.0*C

### ISSUE THREAD

**Issue by databrb-com** [quen0n/DHT11-DHT22-STM32-HAL#2]
thanks for your code. i have problem with blue pill or black pill with DHT11. use all your code with change anything. i can get int only. always xx.0*C. can you advice what wrong?
```
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%
Temp: 30.0*С, Hum: 53.0%

```

**Comment by quen0n** [comment]
Hello. DHT11 always transmits decimal zeros. Fractional part is supported in DHT22 and its analogues.
Datasheet DHT11, page 2
https://www.electronicoscaldas.com/datasheet/DHT11_Aosong.pdf
