### ISSUE TITLE
2 DHT11 sensors

### ISSUE THREAD

**Issue by Duhamoras** [quen0n/DHT11-DHT22-STM32-HAL#4]
It is available to use two same sensors?

**Comment by quen0n** [comment]
Yes, just add another sensor to the menu

**Comment by Duhamoras** [comment]
I'm trying to do that, but can't understad, why it's not working, Pins are conected properly, because with one sensor while testing both works. But when trying to get data from two sensors I get only from one. Maybe you can help a little bit and show, what to add to code to get data?

**Comment by quen0n** [comment]
Oops, I messed up the repositories

Show your code that you use to get data from sensors

**Comment by Duhamoras** [comment]
I'm just using Your code with DHT11 and trying to read second DHT11 sensor. Just trying a lot of variations, because I'm not good at programing. At first I need to know that do I need to change anything in DHT.c or DHT.h files or just make changes in my main.c file?

My main.c file moments:

/* USER CODE BEGIN 1 */

	 DHT_sensor livingRoom = {GPIOA, GPIO_PIN_1, DHT11, GPIO_NOPULL};
	 DHT_sensor bedRoom = {GPIOC, GPIO_PIN_0, DHT11, GPIO_NOPULL};

  /* USER CODE END 1 */



 while (1)
  {
    
//Receiving data from the sensor
    DHT_data d = DHT_getData (&livingRoom); 
    DHT_data e = DHT_getData (&bedRoom);
}


Today I have done a lot of changes, but now can't remember what I done, because it not worked

**Comment by quen0n** [comment]
No, you don't need to make any changes to DHT.h and DHT.c. If you connect the sensors correctly and specify the connection port correctly, then everything should work

**Comment by Duhamoras** [comment]
Conections are good, I already check that. So, maybe you have idea where could be problem? I use that code I already wrote there but still get data from first one. Second one send -128 in all cases..

**Comment by Duhamoras** [comment]
Tiredness is bad thing... All day working on project and did a stupid mistake in code. Everything  works good now, thanks for Your time and a good work on these sensors:)

**Comment by quen0n** [comment]
I'm glad you made it

**Comment by Duhamoras** [comment]
It was easy job and I managed to fail it
